"""change jar unique constraint

Revision ID: 1d1604507cb2
Revises: 46ebf122fd62
Create Date: 2024-04-10 22:50:13.466887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d1604507cb2'
down_revision: Union[str, None] = '46ebf122fd62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('jars_long_jar_id_key', 'jars', type_='unique')
    op.create_unique_constraint('_project_jar_uc', 'jars', ['long_jar_id', 'project_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_project_jar_uc', 'jars', type_='unique')
    op.create_unique_constraint('jars_long_jar_id_key', 'jars', ['long_jar_id'])
    # ### end Alembic commands ###
