"""make project desc optional and add active field

Revision ID: 4939904be8c4
Revises: dfef129e8e47
Create Date: 2024-03-28 18:48:42.210976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4939904be8c4'
down_revision: Union[str, None] = 'dfef129e8e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('active', sa.Boolean(), nullable=True))
    op.execute("UPDATE projects SET active = TRUE")
    op.alter_column('projects', 'active', nullable=False)
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('projects', 'active')
    # ### end Alembic commands ###
